### ISSUE TITLE
files seem broken after datalad merge

### ISSUE THREAD

**Issue by sheyma** [datalad-datasets/hcp_MNI_T1w#1]
thanks for uploading **xfms** dirs there!

After typing this command, **xfms** were all there:

`$ datalad update --merge
`
However, the files in there look to be broken:

![Screenshot_2020-09-28_16-11-29](https://user-images.githubusercontent.com/2557416/94443314-4db6f680-01a5-11eb-8a53-8c20a3f1458f.png)

We had this issue a while ago, but I have lost our history unfortunately :(

**Comment by adswa** [comment]
Hi @sheyma - could you please try to "get" the files? :) I suspect that this is just a representation of the "empty" files that don't yet have file content retrieved.

**Comment by sheyma** [comment]
yeap, "get" helped a lot :=)
...just read the datalad manual finally, that I should have done at the beginning.

Please feel free to close the issue,
Thanks a lot @adswa !!!

**Comment by adswa** [comment]
Glad to hear this! Always happy if things are resolved so easily for everyone involved :)
