### ISSUE TITLE
adding some more files in here

### ISSUE THREAD

**Issue by sheyma** [datalad-datasets/hcp_MNI_T1w#2]
Hello hello,

would it be possible to add some more files in hcp_MNI_T1w for each subject:

T1w_restore_brain.nii.gz
T2w_restore.nii.gz
T2w_restore_brain.nii.gz

Thanks in advance!
BTW, if it's explained somewhere in datalad tutorial, ie. how the user could do that alone with the HCP dataset, please feel free to point me there. I'd like to learn it as well.

**Comment by adswa** [comment]
I think https://github.com/datalad-datasets/hcp-structural-preprocessed could maybe already be what you are looking for?

**Comment by sheyma** [comment]
Actually not, the link has images in native space.
However, I don't think any files anymore. Since I managed to register images in hcp-structural-preprocessed to mni with the transormation files you already provided hcp_MNI_T1w/<subjid>/MNINonLinear/xfms/ . This was great!
So we can close this issue.
Thanks a lot!

**Comment by adswa** [comment]
Great!
